### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by StasKarpenko1991** [StasKarpenko1991/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Stas-karpenko** [comment]
e-mail: stas.karpenko.1991@gmail.com
facebook:https://www.facebook.com/profile.php?id=100007208086528
